from os import getenv

LAN_HOST = "0.0.0.0"
LOCAL_HOST = "127.0.0.1"
SERVER_HOST = getenv("WINDOWS_HOST", LAN_HOST)
SERVER_PORT = 8000
URL_HOST = LOCAL_HOST if SERVER_HOST == LAN_HOST else SERVER_HOST
URL = f"http://{'127.0.0.1' if SERVER_HOST == '0.0.0.0' else SERVER_HOST}:{SERVER_PORT}"
