[project]
name = "wsl-bridge"
version = "0.1.0"
description = "A FastAPI server that works like a bridge between Windows Host machine and WSL instance."
readme = "README.md"
authors = [
    { name = "SeshuTarapatla", email = "seshu.tarapatla@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.136.0",
    "my-modules",
    "uvicorn>=0.44.0",
]

[project.scripts]
wsl-bridge = "wsl_bridge:main"

[build-system]
requires = ["uv_build>=0.11.2,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]

[tool.uv.sources]
my-modules = { git = "https://github.com/SeshuTarapatla/my-modules.git" }
